# Generated by Django 4.2 on 2024-01-20 15:52
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True,
                                     primary_key=True,
                                     serialize=False,
                                     verbose_name='ID')),
                ('created_at',
                 models.DateTimeField(db_index=True,
                                      default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('license',
                 models.ImageField(blank=True,
                                   null=True,
                                   upload_to='experts/licenses/')),
                ('bad_background', models.BooleanField(default=False)),
                ('bad_background_license',
                 models.ImageField(blank=True,
                                   null=True,
                                   upload_to='experts/bad_backgrounds/')),
                ('category',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='services.servicecategory')),
                ('city',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='services.city')),
                ('province',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='services.province')),
                ('user',
                 models.OneToOneField(
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='expert',
                     to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True,
                                     primary_key=True,
                                     serialize=False,
                                     verbose_name='ID')),
                ('created_at',
                 models.DateTimeField(db_index=True,
                                      default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expert',
                 models.OneToOneField(
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='warranty',
                     to='experts.expert')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True,
                                     primary_key=True,
                                     serialize=False,
                                     verbose_name='ID')),
                ('created_at',
                 models.DateTimeField(db_index=True,
                                      default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='experts/samples/')),
                ('description', models.CharField(max_length=2000)),
                ('category',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='services.servicecategory')),
                ('expert',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='samples',
                                   to='experts.expert')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True,
                                     primary_key=True,
                                     serialize=False,
                                     verbose_name='ID')),
                ('created_at',
                 models.DateTimeField(db_index=True,
                                      default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expert',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='experts.expert')),
                ('user',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='bookmark',
                                   to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AvailableTimeExpert',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True,
                                     primary_key=True,
                                     serialize=False,
                                     verbose_name='ID')),
                ('created_at',
                 models.DateTimeField(db_index=True,
                                      default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_time',
                 models.TimeField(default=django.utils.timezone.now)),
                ('end_time',
                 models.TimeField(default=django.utils.timezone.now)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('expert',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='available',
                                   to='experts.expert')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
