# Generated by Django 4.2 on 2024-01-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('BAN', 'Ban')], default='ACTIVE', max_length=8),
        ),
    ]
