# Generated by Django 4.2 on 2024-01-22 09:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('experts', '0002_expert_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warranty',
            options={'verbose_name_plural': 'Warranties'},
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('user', 'expert')},
        ),
    ]
