# Generated by Django 4.2 on 2024-01-22 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0004_remove_expert_category_expertskill_expert_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertskill',
            name='expert',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='skill_expert', to='experts.expert'),
        ),
    ]
