# Generated by Django 4.2 on 2024-01-22 10:18
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0005_alter_expertskill_expert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='skill',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='expert_skill',
                to='experts.expertskill'),
        ),
    ]
