# Generated by Django 4.2 on 2024-01-22 10:46
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0006_alter_expert_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expert',
            name='skill',
        ),
    ]
