# Generated by Django 4.2 on 2024-01-22 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0007_remove_expert_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertskill',
            name='expert',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='experts.expert'),
        ),
    ]
