# Generated by Django 4.2 on 2024-01-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0008_alter_expertskill_expert'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='expert_code',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True, unique=True),
        ),
    ]
