# Generated by Django 4.2 on 2024-01-26 08:04

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bucket_name', models.CharField(max_length=32)),
                ('file', models.CharField(max_length=1024)),
                ('extra', models.JSONField(blank=True, null=True)),
                ('type',
                 models.CharField(choices=[('VIDEO', 'Video'), ('IMAGE', 'Image')], default='IMAGE', max_length=5)),
                ('illegal', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medias',
                                           to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
