# Generated by Django 4.2 on 2024-01-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('medias', '0002_media_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='_file',
            field=models.FileField(blank=True, null=True, upload_to='admin/'),
        ),
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='usage',
            field=models.CharField(
                choices=[('0', 'Admin Avatar'), ('1', 'Expert Avatar'), ('2', 'User Avatar'), ('3', 'Admin'),
                         ('4', 'Service'), ('5', 'Order')], default='2', max_length=1),
        ),
    ]
