# Generated by Django 4.2 on 2024-01-26 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('medias', '0004_alter_media_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.CharField(blank=True, db_index=True, max_length=1024, null=True),
        ),
    ]
