# Generated by Django 4.2 on 2024-01-13 05:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=64, null=True)),
                ('slug', models.SlugField(allow_unicode=True, max_length=32, unique=True)),
                ('caption', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.TextField()),
                ('weight', models.PositiveSmallIntegerField()),
                ('image', models.ImageField(upload_to='slider/')),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('weight',),
            },
        ),
    ]
