# Generated by Django 4.2 on 2024-01-20 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import herfeei.orders.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('experts', '__first__'),
        ('discounts', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDateTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('now', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('order_track_id', models.CharField(db_index=True, default=herfeei.orders.models.generate_track_token, max_length=10, unique=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='discounts.discount')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='experts.expert')),
                ('for_other', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('order_date_time', models.ManyToManyField(to='orders.orderdatetime')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='services.service')),
                ('user_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='services.useranswer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
