# Generated by Django 4.2 on 2024-01-21 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('orders', '0002_order_email_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_address',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='users.address'),
            preserve_default=False,
        ),
    ]
