# Generated by Django 4.2 on 2024-01-22 11:14

from django.db import migrations, models
import django.db.models.deletion
import herfeei.orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('experts', '0008_alter_expertskill_expert'),
        ('services', '0001_initial'),
        ('orders', '0003_order_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='experts.expert'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_track_id',
            field=models.CharField(blank=True, db_index=True, default=herfeei.orders.models.generate_track_token, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='services.service'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='users.address'),
        ),
    ]
