# Generated by Django 4.2 on 2024-01-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('orders', '0004_alter_order_expert_alter_order_order_track_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('NOTIFIED', 'Notified')], default='CREATED',
                                   max_length=10),
        ),
    ]
