# Generated by Django 4.2 on 2024-01-20 15:51
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True,
                                     primary_key=True,
                                     serialize=False,
                                     verbose_name='ID')),
                ('created_at',
                 models.DateTimeField(db_index=True,
                                      default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=64)),
                ('slug',
                 models.SlugField(allow_unicode=True,
                                  max_length=32,
                                  unique=True)),
                ('icon',
                 models.ImageField(blank=True,
                                   null=True,
                                   upload_to='icons/contacts/')),
                ('content', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FaqCategory',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True,
                                     primary_key=True,
                                     serialize=False,
                                     verbose_name='ID')),
                ('created_at',
                 models.DateTimeField(db_index=True,
                                      default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=64)),
                ('slug',
                 models.SlugField(allow_unicode=True,
                                  max_length=32,
                                  unique=True)),
                ('icon', models.CharField(blank=True,
                                          max_length=512,
                                          null=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ Category',
                'verbose_name_plural': 'FAQ Categories',
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True,
                                     primary_key=True,
                                     serialize=False,
                                     verbose_name='ID')),
                ('created_at',
                 models.DateTimeField(db_index=True,
                                      default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=64)),
                ('subtitle', models.CharField(max_length=128)),
                ('slug',
                 models.SlugField(allow_unicode=True,
                                  max_length=32,
                                  unique=True)),
                ('details', models.TextField()),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True,
                                     primary_key=True,
                                     serialize=False,
                                     verbose_name='ID')),
                ('created_at',
                 models.DateTimeField(db_index=True,
                                      default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=64)),
                ('slug',
                 models.SlugField(allow_unicode=True,
                                  max_length=32,
                                  unique=True)),
                ('details', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('category',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='faq',
                                   to='dashboards.faqcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
