# Generated by Django 4.2 on 2024-01-08 14:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0002_faqcategory_rename_enable_rule_status_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=64)),
                ('slug', models.SlugField(allow_unicode=True, max_length=32, unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icons/contacts/')),
                ('content', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
