# Generated by Django 4.2 on 2024-01-20 15:51
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experts', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True,
                                     primary_key=True,
                                     serialize=False,
                                     verbose_name='ID')),
                ('created_at',
                 models.DateTimeField(db_index=True,
                                      default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rate', models.PositiveSmallIntegerField(default=3)),
                ('description', models.CharField(max_length=512)),
                ('status',
                 models.CharField(choices=[('APPROVE', 'Approve'),
                                           ('REJECT', 'Reject'),
                                           ('WAIT', 'Wait')],
                                  default='WAIT',
                                  max_length=7)),
                ('expert',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='comments',
                                   to='experts.expert')),
                ('user',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='comments',
                                   to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
