# Generated by Django 4.2 on 2024-01-08 15:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=128)),
                ('slug', models.SlugField(allow_unicode=True, max_length=32, unique=True)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('icon', models.ImageField(upload_to='icons/services/')),
                ('weight', models.PositiveSmallIntegerField()),
                ('is_sub_category', models.BooleanField(default=False)),
                ('parent_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='services.servicecategory')),
            ],
            options={
                'verbose_name_plural': 'Service Categories',
            },
        ),
    ]
