# Generated by Django 4.2 on 2024-01-08 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_servicecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='services/covers/'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service', to='services.servicecategory'),
        ),
    ]
