# Generated by Django 4.2 on 2024-01-09 13:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_remove_servicecategory_cover_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceItemPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=64)),
                ('slug', models.SlugField(allow_unicode=True, max_length=32, unique=True)),
                ('start_range', models.PositiveIntegerField()),
                ('end_range', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('introduce', models.TextField()),
                ('guide', models.TextField()),
                ('rule', models.TextField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price', to='services.serviceitemprice')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category', to='services.servicecategory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
