# Generated by Django 4.2 on 2024-01-09 14:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_serviceitemprice_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='item',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service',
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item', to='services.servicecategory')),
                ('item_price', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price', to='services.serviceitemprice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='service',
            name='items',
            field=models.ManyToManyField(to='services.serviceitem'),
        ),
    ]
