# Generated by Django 4.2 on 2024-01-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_remove_service_item_remove_service_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceitem',
            name='item_price',
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='end_range',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=0, max_length=32, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='start_range',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='title',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ServiceItemPrice',
        ),
    ]
