# Generated by Django 4.2 on 2024-01-09 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_remove_serviceitem_item_price_serviceitem_end_range_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceitem',
            name='category',
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='item', to='services.servicecategory'),
            preserve_default=False,
        ),
    ]
