# Generated by Django 4.2 on 2024-01-09 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_remove_serviceitem_category_service_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service', to='services.servicecategory'),
        ),
        migrations.AlterField(
            model_name='service',
            name='items',
            field=models.ManyToManyField(related_name='prices', to='services.serviceitem'),
        ),
    ]
