# Generated by Django 4.2 on 2024-01-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='posts_count',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='subscriber_count',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='subscription_count',
        ),
        migrations.AddField(
            model_name='baseuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('USER', 'User'), ('EXPERT', 'Expert')], default='USER', max_length=9),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='username',
            field=models.CharField(db_index=True, default=0, max_length=10, unique=True, verbose_name='Phone number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True, verbose_name='email address'),
        ),
        migrations.AlterUniqueTogether(
            name='baseuser',
            unique_together={('username', 'email')},
        ),
        migrations.RemoveField(
            model_name='baseuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='baseuser',
            name='is_admin',
        ),
    ]
