# Generated by Django 4.2 on 2024-01-06 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_bio_remove_profile_posts_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuser',
            name='is_superuser',
        ),
    ]
