# Generated by Django 4.2 on 2024-01-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_created_at_profile_updated_at_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=64, unique=True),
        ),
    ]
