# Generated by Django 4.2 on 2024-01-20 15:51
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseNotification',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True,
                                     primary_key=True,
                                     serialize=False,
                                     verbose_name='ID')),
                ('created_at',
                 models.DateTimeField(db_index=True,
                                      default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=64)),
                ('slug',
                 models.SlugField(allow_unicode=True,
                                  max_length=64,
                                  unique=True)),
                ('level',
                 models.CharField(choices=[('DANGER', 'Danger'),
                                           ('SUCCESS', 'Success'),
                                           ('WARNING', 'Warning'),
                                           ('INFO', 'Info')],
                                  default='INFO',
                                  max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotificationCategory',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True,
                                     primary_key=True,
                                     serialize=False,
                                     verbose_name='ID')),
                ('created_at',
                 models.DateTimeField(db_index=True,
                                      default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=64)),
                ('slug',
                 models.SlugField(allow_unicode=True,
                                  max_length=64,
                                  unique=True)),
            ],
            options={
                'verbose_name_plural': 'Notification Categories',
            },
        ),
        migrations.CreateModel(
            name='NotificationOption',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True,
                                     primary_key=True,
                                     serialize=False,
                                     verbose_name='ID')),
                ('created_at',
                 models.DateTimeField(db_index=True,
                                      default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.CharField(max_length=128)),
                ('value', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True,
                                     primary_key=True,
                                     serialize=False,
                                     verbose_name='ID')),
                ('created_at',
                 models.DateTimeField(db_index=True,
                                      default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status',
                 models.CharField(choices=[('READ', 'Read'),
                                           ('UNREAD', 'Unread')],
                                  default='UNREAD',
                                  max_length=6)),
                ('notification',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                   related_name='user',
                                   to='notifications.basenotification')),
                ('options',
                 models.ManyToManyField(
                     related_name='user_notifications',
                     to='notifications.notificationoption')),
                ('user',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='notifications',
                                   to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='basenotification',
            name='category',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='notification',
                to='notifications.notificationcategory'),
        ),
    ]
