# Generated by Django 4.2 on 2024-01-11 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_basenotification_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basenotification',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='notifications.notificationcategory'),
        ),
    ]
