# Generated by Django 4.2 on 2024-01-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_alter_notificationcategory_depth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationcategory',
            name='depth',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notificationcategory',
            name='path',
            field=models.CharField(default=0, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='options',
            field=models.ManyToManyField(related_name='user_notifications', to='notifications.notificationoption'),
        ),
    ]
